a = int(input("give a number greater than 26\n>"))
print(a > 26)
b = int(input("what number is more than 2\n>"))
print(b > 2)
c = int(input("what number is less than 5\n>"))
print(c < 5)
d = int(input("what number is less than 56\n>"))
print(d < 56)
e = int(input("what number is higher than 1000000"))
print(e > 1000000)